// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phoneTypeWrap.proto

package pb.protobuf;

public final class PhoneTypeProtos {
  private PhoneTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PhoneTypeWrap
      implements com.google.protobuf.ProtocolMessageEnum {
    MOBILE(0, 0),
    HOME(1, 1),
    WORK(2, 2),
    ;
    
    public static final int MOBILE_VALUE = 0;
    public static final int HOME_VALUE = 1;
    public static final int WORK_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static PhoneTypeWrap valueOf(int value) {
      switch (value) {
        case 0: return MOBILE;
        case 1: return HOME;
        case 2: return WORK;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PhoneTypeWrap>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PhoneTypeWrap>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneTypeWrap>() {
            public PhoneTypeWrap findValueByNumber(int number) {
              return PhoneTypeWrap.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pb.protobuf.PhoneTypeProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PhoneTypeWrap[] VALUES = {
      MOBILE, HOME, WORK, 
    };
    
    public static PhoneTypeWrap valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private PhoneTypeWrap(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:tutorial.PhoneTypeWrap)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023phoneTypeWrap.proto\022\010tutorial*/\n\rPhone" +
      "TypeWrap\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002" +
      "B\036\n\013pb.protobufB\017PhoneTypeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
