// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phoneNumberWrap.proto

package pb.protobuf;

public final class PhoneNumberProtos {
  private PhoneNumberProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PhoneNumberWrapOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string number = 1;
    boolean hasNumber();
    String getNumber();
    
    // optional .tutorial.PhoneTypeWrap type = 2 [default = HOME];
    boolean hasType();
    pb.protobuf.PhoneTypeProtos.PhoneTypeWrap getType();
  }
  public static final class PhoneNumberWrap extends
      com.google.protobuf.GeneratedMessage
      implements PhoneNumberWrapOrBuilder {
    // Use PhoneNumberWrap.newBuilder() to construct.
    private PhoneNumberWrap(Builder builder) {
      super(builder);
    }
    private PhoneNumberWrap(boolean noInit) {}
    
    private static final PhoneNumberWrap defaultInstance;
    public static PhoneNumberWrap getDefaultInstance() {
      return defaultInstance;
    }
    
    public PhoneNumberWrap getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.protobuf.PhoneNumberProtos.internal_static_tutorial_PhoneNumberWrap_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.protobuf.PhoneNumberProtos.internal_static_tutorial_PhoneNumberWrap_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string number = 1;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private Object number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNumber() {
      Object ref = number_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          number_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNumberBytes() {
      Object ref = number_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .tutorial.PhoneTypeWrap type = 2 [default = HOME];
    public static final int TYPE_FIELD_NUMBER = 2;
    private pb.protobuf.PhoneTypeProtos.PhoneTypeWrap type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public pb.protobuf.PhoneTypeProtos.PhoneTypeWrap getType() {
      return type_;
    }
    
    private void initFields() {
      number_ = "";
      type_ = pb.protobuf.PhoneTypeProtos.PhoneTypeWrap.HOME;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pb.protobuf.PhoneNumberProtos.PhoneNumberWrap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pb.protobuf.PhoneNumberProtos.PhoneNumberWrap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pb.protobuf.PhoneNumberProtos.PhoneNumberWrapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.protobuf.PhoneNumberProtos.internal_static_tutorial_PhoneNumberWrap_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.protobuf.PhoneNumberProtos.internal_static_tutorial_PhoneNumberWrap_fieldAccessorTable;
      }
      
      // Construct using pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = pb.protobuf.PhoneTypeProtos.PhoneTypeWrap.HOME;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.getDescriptor();
      }
      
      public pb.protobuf.PhoneNumberProtos.PhoneNumberWrap getDefaultInstanceForType() {
        return pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.getDefaultInstance();
      }
      
      public pb.protobuf.PhoneNumberProtos.PhoneNumberWrap build() {
        pb.protobuf.PhoneNumberProtos.PhoneNumberWrap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pb.protobuf.PhoneNumberProtos.PhoneNumberWrap buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pb.protobuf.PhoneNumberProtos.PhoneNumberWrap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pb.protobuf.PhoneNumberProtos.PhoneNumberWrap buildPartial() {
        pb.protobuf.PhoneNumberProtos.PhoneNumberWrap result = new pb.protobuf.PhoneNumberProtos.PhoneNumberWrap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.protobuf.PhoneNumberProtos.PhoneNumberWrap) {
          return mergeFrom((pb.protobuf.PhoneNumberProtos.PhoneNumberWrap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pb.protobuf.PhoneNumberProtos.PhoneNumberWrap other) {
        if (other == pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumber()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              number_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              pb.protobuf.PhoneTypeProtos.PhoneTypeWrap value = pb.protobuf.PhoneTypeProtos.PhoneTypeWrap.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string number = 1;
      private Object number_ = "";
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNumber() {
        Object ref = number_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      void setNumber(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
      }
      
      // optional .tutorial.PhoneTypeWrap type = 2 [default = HOME];
      private pb.protobuf.PhoneTypeProtos.PhoneTypeWrap type_ = pb.protobuf.PhoneTypeProtos.PhoneTypeWrap.HOME;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public pb.protobuf.PhoneTypeProtos.PhoneTypeWrap getType() {
        return type_;
      }
      public Builder setType(pb.protobuf.PhoneTypeProtos.PhoneTypeWrap value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = pb.protobuf.PhoneTypeProtos.PhoneTypeWrap.HOME;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.PhoneNumberWrap)
    }
    
    static {
      defaultInstance = new PhoneNumberWrap(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.PhoneNumberWrap)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_PhoneNumberWrap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_PhoneNumberWrap_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025phoneNumberWrap.proto\022\010tutorial\032\023phone" +
      "TypeWrap.proto\"N\n\017PhoneNumberWrap\022\016\n\006num" +
      "ber\030\001 \002(\t\022+\n\004type\030\002 \001(\0162\027.tutorial.Phone" +
      "TypeWrap:\004HOMEB \n\013pb.protobufB\021PhoneNumb" +
      "erProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_PhoneNumberWrap_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_PhoneNumberWrap_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_PhoneNumberWrap_descriptor,
              new java.lang.String[] { "Number", "Type", },
              pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.class,
              pb.protobuf.PhoneNumberProtos.PhoneNumberWrap.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.protobuf.PhoneTypeProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
